package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class GenerarProductoController {
	@FXML
	private TextField IdTxt;
	@FXML
	private TextField StockTxt;
	@FXML
	private TextField DescripcionTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ValorTxt;
	@FXML
	private Button GenerarProductoBtn;

	// Event Listener on Button[#GenerarProductoBtn].onMouseClicked
	@FXML
	public void ClickGenerarProducto(MouseEvent event) {
		// TODO Autogenerated
	}
}
