package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GenerarVentaController {
	@FXML
	private TextField ProductoTxt;
	@FXML
	private TextField CedEmpleadoTxt;
	@FXML
	private TextField CedClienteTxt;
	@FXML
	private TextField CantidadTxt;
	@FXML
	private TextField IdTxt;
	@FXML
	private Button GenerarBtn;
	@FXML
	private Button VolverBtn;
	@FXML
	private TextField FechaTxt;

	// Event Listener on Button[#GenerarBtn].onMouseClicked
	@FXML
	public void ClickGenerar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#VolverBtn].onMouseClicked
	@FXML
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
