package vista;

import java.sql.SQLException;

import application.CRUDEmpleado;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GenerarEmpleadoController {
	@FXML
	private TextField CedulaTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ApellidoTxt;
	@FXML
	private TextField TelefonoTxt;
	@FXML
	private TextField DireccionTxt;
	@FXML
	private Button GenerarEmpleadoBtn;
	@FXML
	private TextField PuestoTxt;
	@FXML
	private Button VolverBtn;
	private CRUDEmpleado Create;

	// Event Listener on Button[#GenerarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickGenerarEmpleado(MouseEvent event) throws SQLException {
		// TODO Autogenerated
		Create = new CRUDEmpleado(this.CedulaTxt,this.NombreTxt,this.ApellidoTxt,this.TelefonoTxt,this.DireccionTxt);
	}
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
