package vista;

import datos.BD;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class LoginController {
	@FXML
	private TextField UsuarioTxt;
	@FXML
	private PasswordField ContraseñaTxt;
	@FXML
	private Button IngresarBtn;
	@FXML
	private BD dataprovider = new BD();
	private CargarLoginAdmin LG;

	// Event Listener on Button[#loginBtn].onMouseClicked
	@FXML
	public void ClickIngresar(MouseEvent event) {
		// TODO Autogenerated
		LG = new CargarLoginAdmin((Stage)this.UsuarioTxt.getScene().getWindow());
	}
}