package vista;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ModificarEmpleadoController {
	@FXML
	private Button ModificarBtn;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ApellidoTxt;
	@FXML
	private TextField CedulaTxt;
	@FXML
	private Button BuscarBtn;
	@FXML
	private TableView EmpleadoTable;
	@FXML
	private TableColumn PuestoColumn;
	@FXML
	private TableColumn NombreColumn;
	@FXML
	private TableColumn ApellidoColumn;
	@FXML
	private TableColumn TelefonoColumn;
	@FXML
	private TableColumn DireccionColumn;
	@FXML
	private Button VolverBtn;

	// Event Listener on Button[#ModificarBtn].onMouseClicked
	@FXML
	public void ClickModificar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#BuscarBtn].onMouseClicked
	@FXML
	public void ClickBuscar(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#VolverBtn].onMouseClicked
	@FXML
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
