package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class BuscadorClienteController {
	@FXML
	private Button BuscarBtn;
	@FXML
	private TextField IdTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TableView ClienteTable;
	@FXML
	private TableColumn TipoColumn;
	@FXML
	private TableColumn NumeroColumn;
	@FXML
	private TableColumn NombreColumn;
	@FXML
	private TableColumn ApellidoColumn;
	@FXML
	private TableColumn DireccionColumn;
	@FXML
	private TableColumn TelefonoColumn;
	@FXML
	private Button VolverBtn;


	// Event Listener on Button[#BuscarBtn].onMouseClicked
	@FXML
	public void ClickBuscar(MouseEvent event) {
		// TODO Autogenerated
	}
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
