package application;

import datos.CRUDEmpleado;
import datos.Security;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class EliminarEmpleadoController {
    @FXML
    private Button EliminarBtn;
    @FXML
    private TextField CedulaTxt;
    @FXML
    private Button VolverBtn;
	private CRUDEmpleado CRUDEmpleado;
    public EliminarEmpleadoController() {
        this.CRUDEmpleado = new CRUDEmpleado();}
    @FXML
    void ClickEliminar(MouseEvent event) {
    	String cedula = CedulaTxt.getText();
		boolean data1 = CRUDEmpleado.Eliminar(cedula);
		CedulaTxt.clear();}
    @FXML
    public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		String puesto = Security.ComprobarPuesto().toUpperCase();
		if (puesto.equals("ADMIN")) {
			CargarLoginAdmin LA = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("GERENTE")) {
			CargarLoginGerente LG = new CargarLoginGerente((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("VENDEDOR")) {
			CargarLoginVendedor LV = new CargarLoginVendedor((Stage)this.VolverBtn.getScene().getWindow());}}}