package application;

import datos.CRUDCliente;
import datos.Security;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class EliminarClienteController {
    @FXML
    private Button EliminarBtn;
    @FXML
    private TextField NumeroTxt;
    @FXML
    private Button VolverBtn;
	private CRUDCliente CRUDCliente;
    public EliminarClienteController() {
        this.CRUDCliente = new CRUDCliente();}
    @FXML
    void ClickEliminar(MouseEvent event) {
    	String numero = NumeroTxt.getText();
		boolean data1 = CRUDCliente.Eliminar(numero);
		NumeroTxt.clear();}
    @FXML
    public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		String puesto = Security.ComprobarPuesto().toUpperCase();
		if (puesto.equals("ADMIN")) {
			CargarLoginAdmin LA = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("GERENTE")) {
			CargarLoginGerente LG = new CargarLoginGerente((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("VENDEDOR")) {
			CargarLoginVendedor LV = new CargarLoginVendedor((Stage)this.VolverBtn.getScene().getWindow());}}}

