package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GenerarProductoController {
	@FXML
	private TextField IdTxt;
	@FXML
	private TextField StockTxt;
	@FXML
	private TextField DescripcionTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ValorTxt;
	@FXML
	private Button GenerarProductoBtn;
	@FXML
	private Button VolverBtn;

	// Event Listener on Button[#GenerarProductoBtn].onMouseClicked
	@FXML
	public void ClickGenerarProducto(MouseEvent event) {
		// TODO Autogenerated
	}
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
