package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class GenerarProveedorController {
	@FXML
	private TextField IdTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField TelefonoTxt;
	@FXML
	private TextField DescripcionTxt;
	@FXML
	private Button GenerarProBtn;

	// Event Listener on Button[#GenerarProBtn].onMouseClicked
	@FXML
	public void ClickGenerarProveedor(MouseEvent event) {
		// TODO Autogenerated
	}
}
