package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class GenerarClienteController {
	@FXML
	private TextField NumeroTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ApellidoTxt;
	@FXML
	private TextField TelefonoTxt;
	@FXML
	private TextField DireccionTxt;
	@FXML
	private Button GenerarClienteBtn;
	@FXML
	private TextField TipoDocumentoTxt;

	// Event Listener on Button[#GenerarClienteBtn].onMouseClicked
	@FXML
	public void ClickClienteEmpleado(MouseEvent event) {
		// TODO Autogenerated
	}
}
