package application;

import java.sql.SQLException;

import datos.CRUDVenta;
import datos.Factura;
import datos.Security;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GenerarVentaController {
	@FXML
	private TextField ProductoTxt;
	@FXML
	private TextField CedEmpleadoTxt;
	@FXML
	private TextField CedClienteTxt;
	@FXML
	private TextField CantidadTxt;
	@FXML
	private TextField IdTxt;
	@FXML
	private Button GenerarBtn;
	@FXML
	private Button VolverBtn;
	@FXML
	private TextField FechaTxt;
	private CRUDVenta CRUDVenta;
	public GenerarVentaController() {
        this.CRUDVenta = new CRUDVenta();}
	// Event Listener on Button[#GenerarBtn].onMouseClicked
	@FXML
	public void ClickGenerar(MouseEvent event) throws SQLException {
		// TODO Autogenerated
		String producto = ProductoTxt.getText();
		String cedempleado = CedEmpleadoTxt.getText();
		String docnumcliente = CedClienteTxt.getText();
		String cantidad = CantidadTxt.getText();
		String id = IdTxt.getText();
		String fecha = FechaTxt.getText();
		boolean data1 = CRUDVenta.Crear(id, fecha, cedempleado, docnumcliente);
		FacturaController nuevafactura = new FacturaController(id, cantidad, producto, fecha, cedempleado, docnumcliente);
		CargarFactura CF = new CargarFactura((Stage)this.GenerarBtn.getScene().getWindow());
		ProductoTxt.clear();
		CedEmpleadoTxt.clear();
		CedClienteTxt.clear();
		CantidadTxt.clear();
		IdTxt.clear();
		FechaTxt.clear();}
	// Event Listener on Button[#VolverBtn].onMouseClicked
	@FXML
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		String puesto = Security.ComprobarPuesto().toUpperCase();
		if (puesto.equals("ADMIN")) {
			CargarLoginAdmin LA = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("GERENTE")) {
			CargarLoginGerente LG = new CargarLoginGerente((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("VENDEDOR")) {
			CargarLoginVendedor LV = new CargarLoginVendedor((Stage)this.VolverBtn.getScene().getWindow());}}}
