package application;

import datos.CRUDProducto;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class GenerarProductoController {
	@FXML
	private TextField IdTxt;
	@FXML
	private TextField StockTxt;
	@FXML
	private TextField DescripcionTxt;
	@FXML
	private TextField NombreTxt;
	@FXML
	private TextField ValorTxt;
	@FXML
	private Button GenerarProductoBtn;
	@FXML
	private Button VolverBtn;
	private CRUDProducto CRUDProducto;
	public GenerarProductoController() {
        this.CRUDProducto = new CRUDProducto();}
	// Event Listener on Button[#GenerarProductoBtn].onMouseClicked
	@FXML
	public void ClickGenerarProducto(MouseEvent event) {
		// TODO Autogenerated
		String id = IdTxt.getText();
		String stock = StockTxt.getText();
		String descripcion = DescripcionTxt.getText();
		String nombre = NombreTxt.getText();
		String valor = ValorTxt.getText();
		boolean data1 = CRUDProducto.Crear(id, nombre, stock, descripcion, valor);
		IdTxt.clear();
		StockTxt.clear();
		DescripcionTxt.clear();
		NombreTxt.clear();
		ValorTxt.clear();}
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());}}
