package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class InformeController {
	@FXML
	private TextField ComisionTxt;
	@FXML
	private TextField VentaTotalTxt;
	@FXML
	private TextField ProductoMasTxt;
	@FXML
	private Button VolverBtn;
	@FXML
	private TextField ProductoMenosTxt;
	@FXML
	private TextField VendedorMasTxt;
	@FXML
	private TextField VendedorMenosTxt;

	// Event Listener on Button[#VolverBtn].onMouseClicked
	@FXML
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		CargarLoginAdmin LG = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());
	}
}
