package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

/**
 * Controlador para la vista del panel de control de un gerente.
 */
public class LoginGerenteController {
    @FXML
    private Button ConsultarVentaBtn;
    @FXML
    private Button ConsultarProductoBtn;
    @FXML
    private Button ConsultarEmpleadoBtn;
    @FXML
    private Button InformeBtn;
    @FXML
    private Button ConsultarClienteBtn;
    @FXML
    private Button ConsultarProveedorBtn;

    // Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Consultar Venta".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickConsultarVenta(MouseEvent event) {
        // TODO Autogenerated
        CargarBuscadorVenta CBV = new CargarBuscadorVenta((Stage)this.ConsultarVentaBtn.getScene().getWindow());
    }

    // Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Consultar Producto".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickConsultarProducto(MouseEvent event) {
        // TODO Autogenerated
        CargarBuscadorProducto CBPR = new CargarBuscadorProducto((Stage)this.ConsultarProductoBtn.getScene().getWindow());
    }

    // Event Listener on Button[#ConsultarEmpleadoBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Consultar Empleado".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickConsultarEmpleado(MouseEvent event) {
        // TODO Autogenerated
        CargarBuscadorEmpleado CBE = new CargarBuscadorEmpleado((Stage)this.ConsultarEmpleadoBtn.getScene().getWindow());
    }

    // Event Listener on Button[#InformeBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Informe".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickInforme(MouseEvent event) {
        // TODO Autogenerated
        CargarInforme CI = new CargarInforme((Stage)this.InformeBtn.getScene().getWindow());
    }

    // Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Consultar Cliente".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickConsultarCliente(MouseEvent event) {
        // TODO Autogenerated
        CargarBuscadorCliente CBC = new CargarBuscadorCliente((Stage)this.ConsultarClienteBtn.getScene().getWindow());
    }

    // Event Listener on Button[#ConsultarProveedorBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Consultar Proveedor".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickConsultarProveedor(MouseEvent event) {
        // TODO Autogenerated
        CargarBuscadorProveedor CBPV = new CargarBuscadorProveedor((Stage)this.ConsultarProveedorBtn.getScene().getWindow());
    }
}
