package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class LoginAdminController {
	@FXML
	private Button GenerarVentaBtn;
	@FXML
	private Button ConsultarVentaBtn;
	@FXML
	private Button ModificarEliminarVentaBtn;
	@FXML
	private Button GenerarProductoBtn;
	@FXML
	private Button ConsultarProductoBtn;
	@FXML
	private Button ModificarEliminarProductoBtn;
	@FXML
	private Button GenerarEmpleadoBtn;
	@FXML
	private Button InformeBtn;
	@FXML
	private Button ConsultarEmpleadoBtn;
	@FXML
	private Button ModificarEliminarEmpleadoBtn;
	@FXML
	private Button GenerarProveedorBtn;
	@FXML
	private Button ConsultarProveedorBtn;
	@FXML
	private Button ModificarEliminarProveedorBtn;
	@FXML
	private Button GenerarClienteBtn;
	@FXML
	private Button ConsultarClienteBtn;
	@FXML
	private Button ModificarEliminarClienteBtn;
	
	// Event Listener on Button[#GenerarVentaBtn].onMouseClicked
	@FXML
	public void ClickGenerarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarVenta CGV = new CargarGenerarVenta((Stage)this.GenerarVentaBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
	@FXML
	public void ClickConsultarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorVenta CBV = new CargarBuscadorVenta((Stage)this.ConsultarVentaBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ModificarEliminarVentaBtn].onMouseClicked
	@FXML
	public void ClickModificarEliminarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarVenta CMV = new CargarModificarVenta((Stage)this.ModificarEliminarVentaBtn.getScene().getWindow());
	}
	// Event Listener on Button[#GenerarProductoBtn].onMouseClicked
	@FXML
	public void ClickGenerarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarProducto CGPR = new CargarGenerarProducto((Stage)this.GenerarProductoBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
	@FXML
	public void ClickConsultarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProducto CBPR = new CargarBuscadorProducto((Stage)this.ConsultarProductoBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ModificarEliminarProductoBtn].onMouseClicked
	@FXML
	public void ClickModificarEliminarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarProducto CMPR = new CargarModificarProducto((Stage)this.ModificarEliminarProductoBtn.getScene().getWindow()); 
	}
	// Event Listener on Button[#GenerarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickGenerarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarEmpleado CGE = new CargarGenerarEmpleado((Stage)this.GenerarEmpleadoBtn.getScene().getWindow());
	}
	// Event Listener on Button[#InformeBtn].onMouseClicked
	@FXML
	public void ClickInforme(MouseEvent event) {
		// TODO Autogenerated
		CargarInforme CI = new CargarInforme((Stage)this.InformeBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ConsultarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickConsultarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorEmpleado CBE = new CargarBuscadorEmpleado((Stage)this.ConsultarEmpleadoBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ModificarEliminarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickModificarEliminarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarEmplead CMEE = new CargarModificarEmplead((Stage)this.ModificarEliminarEmpleadoBtn.getScene().getWindow());
	}
	// Event Listener on Button[#GenerarProveedor].onMouseClicked
	@FXML
	public void ClickGenerarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarProveedor CGPV = new CargarGenerarProveedor((Stage)this.GenerarProveedorBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ConsultarProveedorBtn].onMouseClicked
	@FXML
	public void ClickConsultarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProveedor CBPV = new CargarBuscadorProveedor((Stage)this.ConsultarProveedorBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ModificarEliminarProveedorBtn].onMouseClicked
	@FXML
	public void ClickModificarEliminarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarProveedor CMPV = new CargarModificarProveedor((Stage)this.ModificarEliminarProveedorBtn.getScene().getWindow());
	}
	// Event Listener on Button[#GenerarClienteBtn].onMouseClicked
	@FXML
	public void ClickGenerarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarCliente CGC = new CargarGenerarCliente((Stage)this.GenerarClienteBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
	@FXML
	public void ClickConsultarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorCliente CBC = new CargarBuscadorCliente((Stage)this.ConsultarClienteBtn.getScene().getWindow());
	}
	// Event Listener on Button[#ModificarEliminarClienteBtn].onMouseClicked
	@FXML
	public void ClickModificarEliminarCliente(MouseEvent event) {
		// TODO Autogenerated
	}
}