package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class LoginGerenteController {
	@FXML
	private Button ConsultarVentaBtn;
	@FXML
	private Button ConsultarProductoBtn;
	@FXML
	private Button ConsultarEmpleadoBtn;
	@FXML
	private Button InformeBtn;
	@FXML
	private Button ConsultarClienteBtn;
	@FXML
	private Button ConsultarProveedorBtn;

	// Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
	@FXML
	public void ClickConsultarVenta(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
	@FXML
	public void ClickConsultarProducto(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ConsultarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickConsultarEmpleado(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#InformeBtn].onMouseClicked
	@FXML
	public void ClickInforme(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
	@FXML
	public void ClickConsultarCliente(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ConsultarProveedorBtn].onMouseClicked
	@FXML
	public void ClickConsultarProveedor(MouseEvent event) {
		// TODO Autogenerated
	}
}
