package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

/**
 * Controlador para la vista de inicio de sesión.
 */
public class LoginController {
    @FXML
    private TextField UsuarioTxt;
    @FXML
    private PasswordField ContraseñaTxt;
    @FXML
    private Button IngresarBtn;
    private CargarLoginAdmin LA;
    private CargarLoginGerente LG;
    private CargarLoginVendedor LV;
    private static String puesto;

    // Event Listener on Button[#loginBtn].onMouseClicked
    /**
     * Maneja el evento de clic en el botón "Ingresar".
     * @param event El evento del ratón.
     */
    @FXML
    public void ClickIngresar(MouseEvent event) {
        // TODO Autogenerated
        String usuario = UsuarioTxt.getText();
        String contraseña = ContraseñaTxt.getText();
        puesto = ValidarLogin.Validar(usuario, contraseña);
        if (puesto.equals("ADMIN")) {
            LA = new CargarLoginAdmin((Stage)this.UsuarioTxt.getScene().getWindow());
        } else if (puesto.equals("GERENTE")) {
            LG = new CargarLoginGerente((Stage)this.UsuarioTxt.getScene().getWindow());
        } else if (puesto.equals("VENDEDOR")) {
            LV = new CargarLoginVendedor((Stage)this.UsuarioTxt.getScene().getWindow());
        }
    }
}
