package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class LoginAdminController {
	@FXML
	private Button GenerarVentaBtn;
	@FXML
	private Button ConsultarVentaBtn;
	@FXML
	private Button ModificarVentaBtn;
	@FXML
	private Button GenerarProductoBtn;
	@FXML
	private Button ConsultarProductoBtn;
	@FXML
	private Button ModificarProductoBtn;
	@FXML
	private Button GenerarEmpleadoBtn;
	@FXML
	private Button InformeBtn;
	@FXML
	private Button ConsultarEmpleadoBtn;
	@FXML
	private Button ModificarEmpleadoBtn;
	@FXML
	private Button GenerarProveedorBtn;
	@FXML
	private Button ConsultarProveedorBtn;
	@FXML
	private Button ModificarProveedorBtn;
	@FXML
	private Button GenerarClienteBtn;
	@FXML
	private Button ConsultarClienteBtn;
	@FXML
	private Button EliminarClienteBtn;
	@FXML
	private Button EliminarEmpleadoBtn;
	@FXML
	private Button EliminarProductoBtn;
	@FXML
	private Button EliminarProveedorBtn;
	@FXML
	private Button EliminarVentaBtn;
	@FXML
	private Button ModificarClienteBtn;
	
	// Event Listener on Button[#GenerarVentaBtn].onMouseClicked
	@FXML
	public void ClickGenerarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarVenta CGV = new CargarGenerarVenta((Stage)this.GenerarVentaBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
	@FXML
	public void ClickConsultarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorVenta CBV = new CargarBuscadorVenta((Stage)this.ConsultarVentaBtn.getScene().getWindow());}
	// Event Listener on Button[#ModificarEliminarVentaBtn].onMouseClicked
	@FXML
	public void ClickModificarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarVenta CMV = new CargarModificarVenta((Stage)this.ModificarVentaBtn.getScene().getWindow());}
	// Event Listener on Button[#GenerarProductoBtn].onMouseClicked
	@FXML
	public void ClickGenerarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarProducto CGPR = new CargarGenerarProducto((Stage)this.GenerarProductoBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
	@FXML
	public void ClickConsultarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProducto CBPR = new CargarBuscadorProducto((Stage)this.ConsultarProductoBtn.getScene().getWindow());}
	// Event Listener on Button[#ModificarEliminarProductoBtn].onMouseClicked
	@FXML
	public void ClickModificarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarProducto CMPR = new CargarModificarProducto((Stage)this.ModificarProductoBtn.getScene().getWindow()); }
	// Event Listener on Button[#GenerarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickGenerarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarEmpleado CGE = new CargarGenerarEmpleado((Stage)this.GenerarEmpleadoBtn.getScene().getWindow());}
	// Event Listener on Button[#InformeBtn].onMouseClicked
	@FXML
	public void ClickInforme(MouseEvent event) {
		// TODO Autogenerated
		CargarInforme CI = new CargarInforme((Stage)this.InformeBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickConsultarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorEmpleado CBE = new CargarBuscadorEmpleado((Stage)this.ConsultarEmpleadoBtn.getScene().getWindow());}
	// Event Listener on Button[#ModificarEliminarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickModificarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarEmplead CME = new CargarModificarEmplead((Stage)this.ModificarEmpleadoBtn.getScene().getWindow());}
	// Event Listener on Button[#GenerarProveedor].onMouseClicked
	@FXML
	public void ClickGenerarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarProveedor CGPV = new CargarGenerarProveedor((Stage)this.GenerarProveedorBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarProveedorBtn].onMouseClicked
	@FXML
	public void ClickConsultarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProveedor CBPV = new CargarBuscadorProveedor((Stage)this.ConsultarProveedorBtn.getScene().getWindow());}
	// Event Listener on Button[#ModificarEliminarProveedorBtn].onMouseClicked
	@FXML
	public void ClickModificarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarProveedor CMPV = new CargarModificarProveedor((Stage)this.ModificarProveedorBtn.getScene().getWindow());}
	// Event Listener on Button[#GenerarClienteBtn].onMouseClicked
	@FXML
	public void ClickGenerarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarCliente CGC = new CargarGenerarCliente((Stage)this.GenerarClienteBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
	@FXML
	public void ClickConsultarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorCliente CBC = new CargarBuscadorCliente((Stage)this.ConsultarClienteBtn.getScene().getWindow());}
	// Event Listener on Button[#ModificarEliminarClienteBtn].onMouseClicked
	@FXML
	public void ClickModificarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarModificarCliente CMC = new CargarModificarCliente((Stage)this.ModificarClienteBtn.getScene().getWindow());}
	@FXML
	public void ClickEliminarCliente(MouseEvent event) {
		CargarEliminarCliente CEC = new CargarEliminarCliente((Stage)this.EliminarClienteBtn.getScene().getWindow());}
	@FXML
	public void ClickEliminarEmpleado(MouseEvent event) {
		CargarEliminarEmpleado CEE = new CargarEliminarEmpleado((Stage)this.EliminarEmpleadoBtn.getScene().getWindow());}
	@FXML
    public void ClickEliminarProducto(MouseEvent event) {
		CargarEliminarProducto CEPR = new CargarEliminarProducto((Stage)this.EliminarProductoBtn.getScene().getWindow());}
    @FXML
    public void ClickEliminarProveedor(MouseEvent event) {
    	CargarEliminarProveedor CEPV = new CargarEliminarProveedor((Stage)this.EliminarProveedorBtn.getScene().getWindow());}
    @FXML
    public void ClickEliminarVenta(MouseEvent event) {
    	CargarEliminarVenta CEV = new CargarEliminarVenta((Stage)this.EliminarVentaBtn.getScene().getWindow());}}

	    


	    