package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;

public class LoginVendedorController {
	@FXML
	private Button ConsultarProductoBtn;
	@FXML
	private Button GenerarClienteBtn;
	@FXML
	private Button GenerarVentaBtn;
	@FXML
	private Button ConsultarClienteBtn;
	@FXML
	private Button ConsultarVentaBtn;

	// Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
	@FXML
	public void ClickConsultarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProducto CBPR = new CargarBuscadorProducto(null);
	}
	// Event Listener on Button[#GenerarClienteBtn].onMouseClicked
	@FXML
	public void ClickGenerarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarCliente CGC = new CargarGenerarCliente(null);
	}
	// Event Listener on Button[#GenerarVentaBtn].onMouseClicked
	@FXML
	public void ClickGenerarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarGenerarVenta CGV = new CargarGenerarVenta(null);
	}
	// Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
	@FXML
	public void ClickConsultarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorCliente CBC = new CargarBuscadorCliente(null);
	}
	// Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
	@FXML
	public void ClickConsultarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorVenta CBV = new CargarBuscadorVenta(null);
	}
}
