package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class LoginGerenteController {
	@FXML
	private Button ConsultarVentaBtn;
	@FXML
	private Button ConsultarProductoBtn;
	@FXML
	private Button ConsultarEmpleadoBtn;
	@FXML
	private Button InformeBtn;
	@FXML
	private Button ConsultarClienteBtn;
	@FXML
	private Button ConsultarProveedorBtn;

	// Event Listener on Button[#ConsultarVentaBtn].onMouseClicked
	@FXML
	public void ClickConsultarVenta(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorVenta CBV = new CargarBuscadorVenta((Stage)this.ConsultarVentaBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarProductoBtn].onMouseClicked
	@FXML
	public void ClickConsultarProducto(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProducto CBPR = new CargarBuscadorProducto((Stage)this.ConsultarProductoBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarEmpleadoBtn].onMouseClicked
	@FXML
	public void ClickConsultarEmpleado(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorEmpleado CBE = new CargarBuscadorEmpleado((Stage)this.ConsultarEmpleadoBtn.getScene().getWindow());}
	// Event Listener on Button[#InformeBtn].onMouseClicked
	@FXML
	public void ClickInforme(MouseEvent event) {
		// TODO Autogenerated
		CargarInforme CI = new CargarInforme((Stage)this.InformeBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarClienteBtn].onMouseClicked
	@FXML
	public void ClickConsultarCliente(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorCliente CBC = new CargarBuscadorCliente((Stage)this.ConsultarClienteBtn.getScene().getWindow());}
	// Event Listener on Button[#ConsultarProveedorBtn].onMouseClicked
	@FXML
	public void ClickConsultarProveedor(MouseEvent event) {
		// TODO Autogenerated
		CargarBuscadorProveedor CBPV = new CargarBuscadorProveedor((Stage)this.ConsultarProveedorBtn.getScene().getWindow());}}
