package application;

import datos.Security;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;

public class LoginController {
	@FXML
	private TextField UsuarioTxt;
	@FXML
	private PasswordField ContraseñaTxt;
	@FXML
	private Button IngresarBtn;
	@FXML
	private CargarLoginAdmin LA;
	private CargarLoginGerente LG;
	private CargarLoginVendedor LV;

	// Event Listener on Button[#loginBtn].onMouseClicked
	@FXML
	public void ClickIngresar(MouseEvent event) {
		// TODO Autogenerated
		String usuario = UsuarioTxt.getText();
		String contraseña = ContraseñaTxt.getText();
		if (usuario != null && contraseña != null && usuario.equals(contraseña)) {
			String puesto = Security.Seguridad(usuario).toUpperCase();
			if (puesto.equals("ADMIN")) {
				LA = new CargarLoginAdmin((Stage)this.UsuarioTxt.getScene().getWindow());}
			else if (puesto.equals("GERENTE")) {
				LG = new CargarLoginGerente((Stage)this.UsuarioTxt.getScene().getWindow());}
			else if (puesto.equals("VENDEDOR")) {
				LV = new CargarLoginVendedor((Stage)this.UsuarioTxt.getScene().getWindow());}
		}}}