package application;

import java.net.URL;
import java.util.ResourceBundle;

import datos.CRUDProveedor;
import datos.Empleado;
import datos.Proveedor;
import datos.Security;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.cell.TextFieldTableCell;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class ModificarProveedorController implements Initializable {

    @FXML
    private Button BuscarBtn;
    @FXML
    private TextField IdTxt;
    @FXML
    private Button ModificarBtn;
    @FXML
    private TextField NombreTxt;
    @FXML
	private TableView<Proveedor> ProveedorTable;
	@FXML
	private TableColumn<Proveedor, String> IdColumn;
	@FXML
	private TableColumn<Proveedor, String> NombreColumn;
	@FXML
	private TableColumn<Proveedor, String> TelefonoColumn;
	@FXML
	private TableColumn<Proveedor, String> DescripcionColumn;
    @FXML
    private Button VolverBtn;
    private ObservableList<Proveedor> proveedor = FXCollections.observableArrayList();
	private CRUDProveedor CRUDProveedor;
	public ModificarProveedorController() {
        this.CRUDProveedor = new CRUDProveedor();}
	// Event Listener on Button[#BucarBtn].onMouseClicked
    @FXML
    public void ClickBuscar(MouseEvent event) {
		// TODO Autogenerated
		String id = IdTxt.getText();
		String nombre = NombreTxt.getText();	
		this.ProveedorTable.getItems().clear();
		ObservableList<Proveedor> info = FXCollections.observableArrayList(CRUDProveedor.Mostrar(id, nombre));
		this.ProveedorTable.setItems(info);}
    @FXML
	public void ClickModificar(MouseEvent event) {
		// TODO Autogenerated
    	Proveedor proveedor = ProveedorTable.getSelectionModel().getSelectedItem();
        if (proveedor != null) {
        	if (proveedor.isEditado()) {
        		boolean modificar = CRUDProveedor.Modificar(proveedor);      
        		if (modificar) {
        			proveedor.setEditado(false);
        		}}}} 
	public void ClickVolver(MouseEvent event) {
		// TODO Autogenerated
		String puesto = Security.ComprobarPuesto().toUpperCase();
		if (puesto.equals("ADMIN")) {
			CargarLoginAdmin LA = new CargarLoginAdmin((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("GERENTE")) {
			CargarLoginGerente LG = new CargarLoginGerente((Stage)this.VolverBtn.getScene().getWindow());}
		else if (puesto.equals("VENDEDOR")) {
			CargarLoginVendedor LV = new CargarLoginVendedor((Stage)this.VolverBtn.getScene().getWindow());}}
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		ProveedorTable.setEditable(true);
        IdColumn.setCellFactory(TextFieldTableCell.forTableColumn());
        NombreColumn.setCellFactory(TextFieldTableCell.forTableColumn());
        TelefonoColumn.setCellFactory(TextFieldTableCell.forTableColumn());
        DescripcionColumn.setCellFactory(TextFieldTableCell.forTableColumn());
		this.CRUDProveedor = new CRUDProveedor();
		this.IdColumn.setCellValueFactory(new PropertyValueFactory<Proveedor, String>("id"));
		this.NombreColumn.setCellValueFactory(new PropertyValueFactory<Proveedor, String>("nombre"));
		this.TelefonoColumn.setCellValueFactory(new PropertyValueFactory<Proveedor, String>("telefono"));
		this.DescripcionColumn.setCellValueFactory(new PropertyValueFactory<Proveedor, String>("descripcion"));
		ProveedorTable.setItems(this.proveedor);						
        IdColumn.setOnEditCommit(event -> {
        	Proveedor e = event.getRowValue();
            e.setId(event.getNewValue());
            e.setEditado(true);});
        NombreColumn.setOnEditCommit(event -> {
        	Proveedor e = event.getRowValue();
        	e.setNombre(event.getNewValue());
        	e.setEditado(true);});
        TelefonoColumn.setOnEditCommit(event -> {
        	Proveedor e = event.getRowValue();
        	e.setTelefono(event.getNewValue());
        	e.setEditado(true);});  
        DescripcionColumn.setOnEditCommit(event -> {
        	Proveedor e = event.getRowValue();
        	e.setDescripcion(event.getNewValue());
        	e.setEditado(true);});}}

